[features]
seeds = false
skip-lint = false
[programs.localnet]
zkcontract2 = "A4RgxkoFpMWhsZn8DimLckU6c8s93cJRJg8sPKu3jRop"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rahulsrivastava/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
